// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_numeric_stat
double cpp_numeric_stat(NumericVector x, std::string op);
RcppExport SEXP _neurotabs_cpp_numeric_stat(SEXP xSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_numeric_stat(x, op));
    return rcpp_result_gen;
END_RCPP
}
// cpp_matrix_row_stat
NumericVector cpp_matrix_row_stat(NumericMatrix x, std::string op);
RcppExport SEXP _neurotabs_cpp_matrix_row_stat(SEXP xSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_matrix_row_stat(x, op));
    return rcpp_result_gen;
END_RCPP
}
// cpp_accumulate_sum
NumericVector cpp_accumulate_sum(NumericVector acc, NumericVector x);
RcppExport SEXP _neurotabs_cpp_accumulate_sum(SEXP accSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type acc(accSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_accumulate_sum(acc, x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_accumulate_sumsq
NumericVector cpp_accumulate_sumsq(NumericVector acc, NumericVector x);
RcppExport SEXP _neurotabs_cpp_accumulate_sumsq(SEXP accSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type acc(accSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_accumulate_sumsq(acc, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neurotabs_cpp_numeric_stat", (DL_FUNC) &_neurotabs_cpp_numeric_stat, 2},
    {"_neurotabs_cpp_matrix_row_stat", (DL_FUNC) &_neurotabs_cpp_matrix_row_stat, 2},
    {"_neurotabs_cpp_accumulate_sum", (DL_FUNC) &_neurotabs_cpp_accumulate_sum, 2},
    {"_neurotabs_cpp_accumulate_sumsq", (DL_FUNC) &_neurotabs_cpp_accumulate_sumsq, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_neurotabs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
