# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_numeric_stat <- function(x, op) {
    .Call(`_neurotabs_cpp_numeric_stat`, x, op)
}

cpp_matrix_row_stat <- function(x, op) {
    .Call(`_neurotabs_cpp_matrix_row_stat`, x, op)
}

cpp_accumulate_sum <- function(acc, x) {
    .Call(`_neurotabs_cpp_accumulate_sum`, acc, x)
}

cpp_accumulate_sumsq <- function(acc, x) {
    .Call(`_neurotabs_cpp_accumulate_sumsq`, acc, x)
}

